---
- name: create users
  hosts: web
  become: yes
  vars:
    user_name:
      - test1
      - test2
      - test3
  tasks:
    - name: create test users
      user: 
        name: '{{ item }}'  
        comment: Creating test user on all servers
        state: present
     loop: "{{ user_name}}"
    
       